---
language: node_js
node_js:
  - "8.11.1"

sudo: false
dist: trusty

addons:
  chromiun: stable

cache:
  directories:
    - node_modules

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false

script:
  - npm run lint:js
  - npm test
  
after_success: npm run coverage
